import Navbar from '@/components/Navbar'
import './globals.css'
import { RxDashboard } from "react-icons/rx";

export const metadata = {
  title: 'Gestidogs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar menuItem={[{ name: "Dashboard", icon: <RxDashboard /> }]} />
        <div>{children}</div>
      </body>
    </html>
  )
}
